# Generated by Django 3.2 on 2021-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('artist', models.CharField(default='', max_length=100)),
                ('duration', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
